%PRINTPDF  Print PDFs of figures generated by simulation
% printpdf(M, filename)
%

% Aric Wax, 2021-06-02
%

function printPdf(M, filename)

    % Constants
    FONT_SCALE_FACTOR = 0.8;

    % Remove existing file
    if exist(filename, 'file')==2
        delete(filename);
    end

    % Scale and print all enabled figures
    for km = 1:numel(M)
        if M(km).enable

            % Get all scalable axes objects
            hax = get(M(km).hf, 'Children');

            % Scale font sizes
            for kax = 1:numel(hax)
                sizk = get(hax(kax), 'FontSize');
                set(hax(kax), 'FontSize', sizk * FONT_SCALE_FACTOR);
            end

            % Get all scalable text objects
            ht = [];
            for kax = 1:numel(hax)
                ht = cat(1, ht, findobj(get(hax(kax), 'Children'), '-depth', 0, 'Type', 'Text'));
            end

            % Scale font sizes
            for kt = 1:numel(ht)
                sizk = get(ht(kt), 'FontSize');
                set(ht(kt), 'FontSize', sizk * FONT_SCALE_FACTOR);
            end

            % Print, append to PDF
            print(M(km).hf, filename, '-append');

            % Unscale font sizes
            for kt = 1:numel(ht)
                sizk = get(ht(kt), 'FontSize');
                set(ht(kt), 'FontSize', sizk / FONT_SCALE_FACTOR);
            end

            % Unscale font sizes
            for kax = 1:numel(hax)
                sizk = get(hax(kax), 'FontSize');
                set(hax(kax), 'FontSize', sizk / FONT_SCALE_FACTOR);
            end

        end
    end

end
